#!/bin/bash
if [ -d public ]; then
    rm -rf public
fi
npm run prod
cd public
echo www.tokenbrowser.com > CNAME
git init
git remote add gh-pages git@github.com:tokenbrowser/tokenbrowser.github.io.git
git add .
git commit -m "Build on $(date)"
git push --force gh-pages master
